name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add_custom_404:
    runs-on: ubuntu-latest
    needs: build_and_deploy  # Wait for build_and_deploy job to complete

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy 404.html to gh-pages branch
      run: |
        git config --global user.name gh-action
        git config --global user.email gh-action@github.com
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git fetch
        git checkout gh-pages
        git checkout main -- .github/404.html  # Fetch 404.html from .github folder in main branch
        mv .github/404.html ./
        rm -rf .github
        git add 404.html
        git commit -m "Add 404.html to gh-pages branch"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
